In [2]:
import numpy as np  # Import NumPy library with alias 'np'

arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.flatten())
print(arr.ravel())

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [3]:
a = np.array([10,20,30,40])
b= np.array([1,2,3,4])

print(a+b) 
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a **2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [6]:
a = np.array([10,20,30,40])
b= np.array([1,2,3,4])

print(a>b)
print(a==b)
print(b <=2)

[ True  True  True  True]
[False False False False]
[ True  True False False]


In [7]:
np.add(a,b)

array([11, 22, 33, 44])

In [12]:
a = np.array([3,2,9,3])
b= np.array([1,2,3,4])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.mod(a,b))
# print(np.abs(a,b))



[ 4  4 12  7]
[ 2  0  6 -1]
[ 3  4 27 12]
[3.   1.   3.   0.75]
[ 9  4 81  9]
[0 0 0 3]


In [14]:
a = np.array([3,2,9,3])
print(a[0])
print(a[2])

b= np.array([[1,2,3],[3,4,6]])
print(b[1,2])

3
9
6


In [15]:
a = np.array([3,2,9,3])
print(a[-1])
print(a[-2])

3
9


In [17]:
a = np.array([10,20,30,40,50])
print(a[1:4])
print(a[:3])
print(a[2:])

[20 30 40]
[10 20 30]
[30 40 50 60]


In [18]:
a = np.arange(10)
print(a[::2])
print(a[1:8:2])
print(a[::-1])

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [19]:
a = np.array([10,20,30,40,50])
idx = [0,2,4]
print(a[idx])

[10 30 50]


In [22]:
a = np.array([10,20,30,40,50])
mask = a >18
print(mask)
print(a[mask])

[False  True  True  True  True]
[20 30 40 50]


In [25]:
a = np.array([10,20,30,40,50])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a, 75))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))




150
30.0
30.0
14.142135623730951
200.0
10
50
40.0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
150
150


In [28]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.vstack([a,b]))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [37]:
a=np.arange(9)
print(np.split(a,1))

[array([0, 1, 2, 3, 4, 5, 6, 7, 8])]


In [40]:
a= np.array([1,2,3,3])
print(np.unique(a))
a[::-1]

[1 2 3]


array([3, 3, 2, 1])

In [3]:
import numpy as np

marks = np.array([[87,88,89,90,91],[95,98,87,89,92],[76,65,67,72,73],[99,98,89,92,93],[54,56,67,62,60]])

avg = np.mean(marks)
print(avg)

81.16


In [4]:
highest = np.max(marks)
lowest = np.min(marks)

print(highest)
print(lowest)

99
54


In [6]:
std = np.std(marks)
print(std)

14.073180166543738


In [9]:
print(np.where(marks> avg)[0])

[0 0 0 0 0 1 1 1 1 1 3 3 3 3 3]


In [10]:
percentage = (np.sum(marks)/500)*100 
print(percentage)

405.79999999999995
